### PR TITLE
Q.0007 finished

### PR DESCRIPTION
**Pull request by Zeyue**
Tested with python projects, can detect codes lines, inline comment and multiple line comment.
Supposed to support c/cpp and java project.

### CODE REVIEW

**Comment by Zeyue** [comment]
Improve multiple comment detection and support to c files

**Comment by Zeyue** [comment]
https://github.com/Zeyue/python

**Comment by theoegui** [comment]
This is fucking cool.
I need some explaining though lol

Sincerely,

Theo

**Comment by Zeyue** [comment]
Thx! Well, what do you want? An explaination about how to use it?

**Comment by theoegui** [comment]
Yes.an explanation on how to use it please.

Sincerely,

Theodore

**Comment by Zeyue** [comment]
Hi Theodore,

I have just added a README in the repository. Please check it. If it isn't clear, let me know.

Regards,

Zeyue

**Pull request merged**
